apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: sysdig-admission-controller
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/part-of: sysdig-shield
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sysdig-admission-controller
      app.kubernetes.io/component: admission-controller
