apiVersion: v1
kind: Namespace
metadata:
  name: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    name: sysdig-shield
    app.kubernetes.io/name: sysdig-shield
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: sysdig-shield
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
