apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
  namespace: sysdig-shield
data:
  dragent.yaml: |
    collector: collector.sysdigcloud.com
    collector_port: 6443
    ssl: true
    log:
      console_priority: debug
      file_priority: debug
    tags:
      - env:dev
      - component:sysdig-agent
    security:
      enabled: true
    k8s_cluster_name: "dev-cluster"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-shield
data:
  config.yaml: |
    sysdigSecureEndpoint: https://secure.sysdig.com
    webhook:
      port: 8443
    scanner:
      enabled: true
    policies:
      denyOnError: false
    log:
      level: debug
