apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: sysdig-admission-controller
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/part-of: sysdig-shield
