apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sysdig-admission-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: sysdig-admission-controller
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/part-of: sysdig-shield
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sysdig-admission-controller
subjects:
- kind: ServiceAccount
  name: sysdig-admission-controller
  namespace: sysdig-shield
